[build]
target = "index.html"
dist = "dist"
filehash = true

[watch]
watch = ["src", "index.html"]

[serve]
address = "127.0.0.1"
port = 8080
open = true

[[proxy]]
backend = "http://127.0.0.1:3001/ws"
rewrite = "/ws"
ws = true